#############################################################################
# Makefile for building: WASM_Client.js
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  WASM_Client.pro
# Template: app
# Command: /home/stephan/Qt/5.13.1/wasm_32/bin/qmake -o Makefile WASM_Client.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -s ALLOW_MEMORY_GROWTH=1 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O3 -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -W $(DEFINES)
INCPATH       = -I. -I../../Qt/5.13.1/wasm_32/include -I../../Qt/5.13.1/wasm_32/include/QtWidgets -I../../Qt/5.13.1/wasm_32/include/QtGui -I../../Qt/5.13.1/wasm_32/include/QtWebSockets -I../../Qt/5.13.1/wasm_32/include/QtNetwork -I../../Qt/5.13.1/wasm_32/include/QtCore -I. -I/home/stephan/.emscripten_ports/openssl/include -I../../Qt/5.13.1/wasm_32/mkspecs/wasm-emscripten
QMAKE         = /home/stephan/Qt/5.13.1/wasm_32/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/stephan/Qt/5.13.1/wasm_32/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/stephan/Qt/5.13.1/wasm_32/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = WASM_Client.js1.0.0
DISTDIR = /home/stephan/Dokumente/wasm_qt_example/.tmp/WASM_Client.js1.0.0
LINK          = em++
LFLAGS        = -s WASM=1 -s FULL_ES2=1 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --bind -s "BINARYEN_TRAP_MODE='clamp'" -O3 -s ALLOW_MEMORY_GROWTH=1
LIBS          = $(SUBLIBS) /home/stephan/Qt/5.13.1/wasm_32/plugins/platforms/libqwasm.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5EventDispatcherSupport.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5FontDatabaseSupport.a /home/stephan/Qt/5.13.1/wasm_32/lib/libqtfreetype.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5EglSupport.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqgif.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqicns.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqico.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqjpeg.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqtga.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqtiff.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqwbmp.a /home/stephan/Qt/5.13.1/wasm_32/plugins/imageformats/libqwebp.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Widgets.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Gui.a /home/stephan/Qt/5.13.1/wasm_32/lib/libqtlibpng.a /home/stephan/Qt/5.13.1/wasm_32/lib/libqtharfbuzz.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5WebSockets.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Network.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Core.a /home/stephan/Qt/5.13.1/wasm_32/lib/libqtpcre2.a   
AR            = emar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp /home/stephan/Dokumente/wasm_qt_example/wasm_client.js_plugin_import.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		wasm_client.js_plugin_import.o \
		moc_mainwindow.o
DIST          = ../../Qt/5.13.1/wasm_32/mkspecs/features/spec_pre.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/common/sanitize.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/common/gcc-base.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/common/clang.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/qdevice.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/features/device_config.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/qconfig.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qt_functions.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qt_config.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.13.1/wasm_32/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/toolchain.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/default_pre.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/resolve_config.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/default_post.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/wasm/wasm.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/warn_on.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qt.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/resources.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/moc.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/unix/opengl.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/uic.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qmake_use.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/file_copies.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/testcase_targets.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/exceptions.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/yacc.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/lex.prf \
		WASM_Client.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = WASM_Client.js
DESTDIR       = 
TARGET        = WASM_Client.js


first: all
####### Build rules

WASM_Client.js: /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Widgets.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Gui.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5WebSockets.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Network.a /home/stephan/Qt/5.13.1/wasm_32/lib/libQt5Core.a $(OBJECTS)  apphtml appjs appsvg
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: WASM_Client.pro ../../Qt/5.13.1/wasm_32/mkspecs/wasm-emscripten/qmake.conf ../../Qt/5.13.1/wasm_32/mkspecs/features/spec_pre.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/common/sanitize.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/common/gcc-base.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/common/clang.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/qdevice.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/features/device_config.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/qconfig.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qt_functions.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qt_config.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.13.1/wasm_32/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/toolchain.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/default_pre.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/resolve_config.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/default_post.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/wasm/wasm.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/warn_on.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qt.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/resources.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/moc.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/unix/opengl.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/uic.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/qmake_use.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/file_copies.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/testcase_targets.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/exceptions.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/yacc.prf \
		../../Qt/5.13.1/wasm_32/mkspecs/features/lex.prf \
		WASM_Client.pro \
		../../Qt/5.13.1/wasm_32/plugins/platforms/libqwasm.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqgif.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqicns.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqico.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqjpeg.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqtga.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqtiff.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqwbmp.prl \
		../../Qt/5.13.1/wasm_32/plugins/imageformats/libqwebp.prl \
		../../Qt/5.13.1/wasm_32/lib/libQt5Widgets.prl \
		../../Qt/5.13.1/wasm_32/lib/libQt5Gui.prl \
		../../Qt/5.13.1/wasm_32/lib/libQt5WebSockets.prl \
		../../Qt/5.13.1/wasm_32/lib/libQt5Network.prl \
		../../Qt/5.13.1/wasm_32/lib/libQt5Core.prl
	$(QMAKE) -o Makefile WASM_Client.pro
../../Qt/5.13.1/wasm_32/mkspecs/features/spec_pre.prf:
../../Qt/5.13.1/wasm_32/mkspecs/common/sanitize.conf:
../../Qt/5.13.1/wasm_32/mkspecs/common/gcc-base.conf:
../../Qt/5.13.1/wasm_32/mkspecs/common/clang.conf:
../../Qt/5.13.1/wasm_32/mkspecs/qdevice.pri:
../../Qt/5.13.1/wasm_32/mkspecs/features/device_config.prf:
../../Qt/5.13.1/wasm_32/mkspecs/qconfig.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qgif.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qicns.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qico.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtga.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri:
../../Qt/5.13.1/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri:
../../Qt/5.13.1/wasm_32/mkspecs/features/qt_functions.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/qt_config.prf:
../../Qt/5.13.1/wasm_32/mkspecs/wasm-emscripten/qmake.conf:
../../Qt/5.13.1/wasm_32/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.13.1/wasm_32/mkspecs/features/exclusive_builds.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/toolchain.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/default_pre.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/resolve_config.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/default_post.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/wasm/wasm.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/warn_on.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/qt.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/resources.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/moc.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/unix/opengl.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/uic.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/qmake_use.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/file_copies.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/testcase_targets.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/exceptions.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/yacc.prf:
../../Qt/5.13.1/wasm_32/mkspecs/features/lex.prf:
WASM_Client.pro:
../../Qt/5.13.1/wasm_32/plugins/platforms/libqwasm.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqgif.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqicns.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqico.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqjpeg.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqtga.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqtiff.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqwbmp.prl:
../../Qt/5.13.1/wasm_32/plugins/imageformats/libqwebp.prl:
../../Qt/5.13.1/wasm_32/lib/libQt5Widgets.prl:
../../Qt/5.13.1/wasm_32/lib/libQt5Gui.prl:
../../Qt/5.13.1/wasm_32/lib/libQt5WebSockets.prl:
../../Qt/5.13.1/wasm_32/lib/libQt5Network.prl:
../../Qt/5.13.1/wasm_32/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile WASM_Client.pro

qmake_all: FORCE


all: Makefile WASM_Client.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.13.1/wasm_32/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm /home/stephan/Dokumente/wasm_qt_example/wasm_client.js_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: /home/stephan/Qt/5.13.1/wasm_32/plugins/platforms/wasm_shell.html
	sed -e s/@APPNAME@/WASM_Client/g /home/stephan/Qt/5.13.1/wasm_32/plugins/platforms/wasm_shell.html > /home/stephan/Dokumente/wasm_qt_example/WASM_Client.html

appjs: /home/stephan/Qt/5.13.1/wasm_32/plugins/platforms/qtloader.js
	cp -f /home/stephan/Qt/5.13.1/wasm_32/plugins/platforms/qtloader.js /home/stephan/Dokumente/wasm_qt_example

appsvg: /home/stephan/Qt/5.13.1/wasm_32/plugins/platforms/qtlogo.svg
	cp -f /home/stephan/Qt/5.13.1/wasm_32/plugins/platforms/qtlogo.svg /home/stephan/Dokumente/wasm_qt_example

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) WASM_Client.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.13.1/wasm_32/mkspecs/features/data/dummy.cpp
	em++ -pipe -O3 -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.13.1/wasm_32/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QMainWindow \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qmainwindow.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtguiglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qconfig.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtcore-config.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsystemdetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qprocessordetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcompilerdetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtypeinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsysinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlogging.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qflags.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbasicatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qgenericatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_msvc.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qglobalstatic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmutex.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qnumeric.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qversiontagging.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtgui-config.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtwidgets-config.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qwidget.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qwindowdefs.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobjectdefs.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qnamespace.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobject.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstring.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qchar.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbytearray.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qrefcount.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qarraydata.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringliteral.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringalgorithms.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringview.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringbuilder.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qalgorithms.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qiterator.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qhashfunctions.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qpair.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvector.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qpoint.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbytearraylist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringlist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qregexp.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringmatcher.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcoreevent.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qscopedpointer.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmetatype.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvarlengtharray.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcontainerfwd.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobject_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmargins.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpaintdevice.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qrect.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsize.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpalette.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qcolor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qrgb.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qrgba64.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qbrush.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qmatrix.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpolygon.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qregion.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdatastream.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qiodevice.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qline.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtransform.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpainterpath.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qimage.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpixelformat.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpixmap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsharedpointer.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qshareddata.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qhash.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfont.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfontmetrics.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfontinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qcursor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qkeysequence.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qevent.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvariant.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdebug.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtextstream.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlocale.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qset.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcontiguouscache.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qurl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qurlquery.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qfile.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qfiledevice.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qvector2d.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtouchdevice.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtabwidget.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qicon.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QWidget \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QPushButton \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qpushbutton.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkAccessManager \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkrequest.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QSharedDataPointer \
		../../Qt/5.13.1/wasm_32/include/QtCore/QString \
		../../Qt/5.13.1/wasm_32/include/QtCore/QUrl \
		../../Qt/5.13.1/wasm_32/include/QtCore/QVariant \
		../../Qt/5.13.1/wasm_32/include/QtCore/QVector \
		../../Qt/5.13.1/wasm_32/include/QtCore/QObject \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslConfiguration \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslconfiguration.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslerror.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcryptographichash.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdatetime.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qssl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QFlags \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QMetaType \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QLabel \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qlabel.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qframe.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QLineEdit \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qlineedit.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextcursor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextformat.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpen.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextoption.h \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/QWebSocket \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QAbstractSocket \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkRequest \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkProxy \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkproxy.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qhostaddress.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslError \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsockets_global.h \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsocketprotocol.h \
		moc_predefs.h \
		../../Qt/5.13.1/wasm_32/bin/moc
	/home/stephan/Qt/5.13.1/wasm_32/bin/moc $(DEFINES) --include /home/stephan/Dokumente/wasm_qt_example/moc_predefs.h -I/home/stephan/Qt/5.13.1/wasm_32/mkspecs/wasm-emscripten -I/home/stephan/Dokumente/wasm_qt_example -I/home/stephan/Qt/5.13.1/wasm_32/include -I/home/stephan/Qt/5.13.1/wasm_32/include/QtWidgets -I/home/stephan/Qt/5.13.1/wasm_32/include/QtGui -I/home/stephan/Qt/5.13.1/wasm_32/include/QtWebSockets -I/home/stephan/Qt/5.13.1/wasm_32/include/QtNetwork -I/home/stephan/Qt/5.13.1/wasm_32/include/QtCore mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QMainWindow \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qmainwindow.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtguiglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qconfig.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtcore-config.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsystemdetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qprocessordetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcompilerdetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtypeinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsysinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlogging.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qflags.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbasicatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qgenericatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_msvc.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qglobalstatic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmutex.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qnumeric.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qversiontagging.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtgui-config.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtwidgets-config.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qwidget.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qwindowdefs.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobjectdefs.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qnamespace.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobject.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstring.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qchar.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbytearray.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qrefcount.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qarraydata.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringliteral.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringalgorithms.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringview.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringbuilder.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qalgorithms.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qiterator.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qhashfunctions.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qpair.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvector.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qpoint.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbytearraylist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringlist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qregexp.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringmatcher.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcoreevent.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qscopedpointer.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmetatype.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvarlengtharray.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcontainerfwd.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobject_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmargins.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpaintdevice.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qrect.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsize.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpalette.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qcolor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qrgb.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qrgba64.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qbrush.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qmatrix.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpolygon.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qregion.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdatastream.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qiodevice.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qline.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtransform.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpainterpath.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qimage.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpixelformat.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpixmap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsharedpointer.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qshareddata.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qhash.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfont.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfontmetrics.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfontinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qcursor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qkeysequence.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qevent.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvariant.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdebug.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtextstream.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlocale.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qset.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcontiguouscache.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qurl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qurlquery.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qfile.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qfiledevice.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qvector2d.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtouchdevice.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtabwidget.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qicon.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QWidget \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QPushButton \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qpushbutton.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkAccessManager \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkrequest.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QSharedDataPointer \
		../../Qt/5.13.1/wasm_32/include/QtCore/QString \
		../../Qt/5.13.1/wasm_32/include/QtCore/QUrl \
		../../Qt/5.13.1/wasm_32/include/QtCore/QVariant \
		../../Qt/5.13.1/wasm_32/include/QtCore/QVector \
		../../Qt/5.13.1/wasm_32/include/QtCore/QObject \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslConfiguration \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslconfiguration.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslerror.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcryptographichash.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdatetime.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qssl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QFlags \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QMetaType \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QLabel \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qlabel.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qframe.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QLineEdit \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qlineedit.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextcursor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextformat.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpen.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextoption.h \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/QWebSocket \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QAbstractSocket \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkRequest \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkProxy \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkproxy.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qhostaddress.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslError \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsockets_global.h \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsocketprotocol.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QApplication \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qapplication.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcoreapplication.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qeventloop.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qdesktopwidget.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qguiapplication.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QMainWindow \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qmainwindow.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtguiglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qconfig.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtcore-config.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsystemdetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qprocessordetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcompilerdetection.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtypeinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsysinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlogging.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qflags.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbasicatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qgenericatomic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qatomic_msvc.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qglobalstatic.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmutex.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qnumeric.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qversiontagging.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtgui-config.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtwidgets-config.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qwidget.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qwindowdefs.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobjectdefs.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qnamespace.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobject.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstring.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qchar.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbytearray.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qrefcount.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qarraydata.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringliteral.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringalgorithms.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringview.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringbuilder.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qalgorithms.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qiterator.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qhashfunctions.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qpair.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvector.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qpoint.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qbytearraylist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringlist.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qregexp.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qstringmatcher.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcoreevent.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qscopedpointer.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmetatype.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvarlengtharray.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcontainerfwd.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qobject_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmargins.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpaintdevice.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qrect.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsize.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpalette.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qcolor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qrgb.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qrgba64.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qbrush.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qmatrix.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpolygon.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qregion.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdatastream.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qiodevice.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qline.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtransform.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpainterpath.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qimage.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpixelformat.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpixmap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsharedpointer.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qshareddata.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qhash.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfont.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfontmetrics.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qfontinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qcursor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qkeysequence.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qevent.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qvariant.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmap.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdebug.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qtextstream.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qlocale.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qset.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcontiguouscache.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qurl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qurlquery.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qfile.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qfiledevice.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qvector2d.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtouchdevice.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qtabwidget.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qicon.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QWidget \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QPushButton \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qpushbutton.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkAccessManager \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkrequest.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QSharedDataPointer \
		../../Qt/5.13.1/wasm_32/include/QtCore/QString \
		../../Qt/5.13.1/wasm_32/include/QtCore/QUrl \
		../../Qt/5.13.1/wasm_32/include/QtCore/QVariant \
		../../Qt/5.13.1/wasm_32/include/QtCore/QVector \
		../../Qt/5.13.1/wasm_32/include/QtCore/QObject \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslConfiguration \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslconfiguration.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslerror.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qcryptographichash.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdatetime.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qssl.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QFlags \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QMetaType \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QLabel \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qlabel.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qframe.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QLineEdit \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qlineedit.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextcursor.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextformat.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qpen.h \
		../../Qt/5.13.1/wasm_32/include/QtGui/qtextoption.h \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/QWebSocket \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsocket.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QAbstractSocket \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkRequest \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QNetworkProxy \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qnetworkproxy.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/qhostaddress.h \
		../../Qt/5.13.1/wasm_32/include/QtNetwork/QSslError \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsockets_global.h \
		../../Qt/5.13.1/wasm_32/include/QtWebSockets/qwebsocketprotocol.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QDebug \
		../../Qt/5.13.1/wasm_32/include/QtCore/QDir \
		../../Qt/5.13.1/wasm_32/include/QtCore/qdir.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/qfileinfo.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/QFileDialog \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qfiledialog.h \
		../../Qt/5.13.1/wasm_32/include/QtWidgets/qdialog.h \
		../../Qt/5.13.1/wasm_32/include/QtCore/QMetaEnum \
		../../Qt/5.13.1/wasm_32/include/QtCore/qmetaobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

wasm_client.js_plugin_import.o: /home/stephan/Dokumente/wasm_qt_example/wasm_client.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wasm_client.js_plugin_import.o /home/stephan/Dokumente/wasm_qt_example/wasm_client.js_plugin_import.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/WASM_Client/bin || mkdir -p $(INSTALL_ROOT)/opt/WASM_Client/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/WASM_Client/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/WASM_Client/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/WASM_Client/bin/ 


install_js_file: first FORCE
	@test -d $(INSTALL_ROOT)/opt/WASM_Client/bin || mkdir -p $(INSTALL_ROOT)/opt/WASM_Client/bin
	-$(QINSTALL_PROGRAM) /home/stephan/Dokumente/wasm_qt_example/WASM_Client.js $(INSTALL_ROOT)/opt/WASM_Client/bin/WASM_Client.js

uninstall_js_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/WASM_Client/bin/WASM_Client.js
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/WASM_Client/bin/ 


install: install_target install_js_file  FORCE

uninstall: uninstall_target uninstall_js_file  FORCE

FORCE:

